export const NEW_GAME = "NEW_GAME";
export const MARKET_UPDATED = "MARKET_UPDATED";
export const JUMP_TO_SYSTEM = "JUMP_TO_SYSTEM";
export const JUMP_TO_GALAXY = "JUMP_TO_GALAXY";
export const ADD_CASH = "ADD_CASH";
export const SET_HOLD_SIZE = "SET_HOLD_SIZE";
export const BUY_FUEL = "BUY_FUEL";
export const BUY_FROM_MARKET = "BUY_FROM_MARKET";
export const SELL_TO_MARKET = "SELL_TO_MARKET";

export const DISPLAY_FEEDBACK_SUCCESS = "DISPLAY_FEEDBACK_SUCCESS";
export const DISPLAY_FEEDBACK_FAILURE = "DISPLAY_FEEDBACK_FAILURE";
export const DISPLAY_FEEDBACK_INFO = "DISPLAY_FEEDBACK_INFO";

export const USER_COMMAND = "USER_COMMAND";
