export const NEW_GAME = "NEW_GAME";
export const MARKET_UPDATED = "MARKET_UPDATED";
export const JUMP_TO_SYSTEM = "JUMP_TO_SYSTEM";
export const PURCHASE_FUEL = "PURCHASE_FUEL";
export const DISPLAY_FEEDBACK_SUCCESS = "DISPLAY_FEEDBACK_SUCCESS";
export const DISPLAY_FEEDBACK_FAILURE = "DISPLAY_FEEDBACK_FAILURE";
export const DISPLAY_FEEDBACK_INFO = "DISPLAY_FEEDBACK_INFO";
